In [24]:
import cv2
import numpy as np
import alphashape
import matplotlib.pyplot as plt
from typing import Tuple
from skimage.morphology import area_opening, reconstruction, convex_hull_image
from skimage.filters import roberts
from skimage.feature import corner_harris, corner_peaks
from scipy import ndimage

In [10]:
def mask_green_pixels(image: np.ndarray,
                     min_range: Tuple = (36, 25, 25),
                     max_range: Tuple = (70, 255, 255)) -> np.ndarray:
    """
    Process image (loaded as opencv np.array) to get only green regions
    :param image: image as a np.ndarray following cv2 convention
    :param min_range: minimum value of a pixel to be classified as green (in HSV scale)
    :param max_range: maximum value of a pixel to be classified as green (in HSV scale)
    :return: grayscale image with blue pixels indicating green pixels and black pixels rest
    """
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, min_range, max_range)

    im_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    im_gray[mask > 0] = 255
    im_gray[mask == 0] = 0
    return im_gray


def remove_noise(grayscale_img: np.ndarray,
                 area_threshold: int = 400) -> np.ndarray:
    """
    Apply openning morphology to get rid of small white blobs and erosion to get rid of small black holes
    :param grayscale_img: numpy array with shape (nrow, ncol)
    :param area_threshold: threshold for preserving white objects
    :return: grayscale image without noise
    """

    modified = area_opening(image=grayscale_img,
                            area_threshold=area_threshold)
    seed = np.copy(modified)
    seed[1:-1, 1:-1] = modified.max()
    mask = modified
    modified = reconstruction(seed, mask, method='erosion')

    return modified

def get_polygon_coordinates(filtered_image: np.ndarray, apply_convex_hull: bool):
    if apply_convex_hull:
        chull = convex_hull_image(filtered_image)
        filtered_image[chull] = 255
    #edges = roberts(filtered_image)
    coords = corner_peaks(corner_harris(image), min_distance=5, threshold_rel=0.02)
    ## adding edges to end-of-pictures

    return coords

In [32]:
img = cv2.imread('/home/skocznapanda/programming/BSc-soccer-annotator/data/barcelona_valencia_frames/raw_frames/frame_169.jpg')

green = mask_green_pixels(img)
without_noise = remove_noise(green)
chull = convex_hull_image(without_noise)
after_convex = without_noise.copy()
after_convex[chull] = 255

converted = after_convex.astype('int')
converted
labeled_image, num_features = ndimage.label(converted)
# Find the location of all objects
objs = ndimage.find_objects(labeled_image)

In [39]:
objs

[(slice(86, 719, None), slice(0, 1280, None))]

In [22]:
#edges.max()

#for el in contours[0]:
#    original[int(el[0]), int(el[1])] = [0, 0, 255]
#original[combined > 0 ] = [0, 0, 255]


True

In [25]:
dst = cv2.GaussianBlur(imgray,(13,13),cv2.BORDER_DEFAULT)
value, thresh = cv2.threshold(dst, 60, 255, cv2.THRESH_BINARY_INV)
cnts, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

cnts

(array([[[429, 513]],
 
        [[428, 514]],
 
        [[427, 514]],
 
        [[426, 515]],
 
        [[426, 516]],
 
        [[425, 517]],
 
        [[425, 522]],
 
        [[426, 523]],
 
        [[426, 534]],
 
        [[427, 535]],
 
        [[427, 538]],
 
        [[429, 540]],
 
        [[430, 540]],
 
        [[431, 541]],
 
        [[432, 540]],
 
        [[433, 540]],
 
        [[433, 539]],
 
        [[434, 538]],
 
        [[434, 535]],
 
        [[435, 534]],
 
        [[435, 517]],
 
        [[434, 516]],
 
        [[434, 515]],
 
        [[433, 514]],
 
        [[432, 514]],
 
        [[431, 513]]], dtype=int32),
 array([[[952, 466]],
 
        [[951, 467]],
 
        [[950, 467]],
 
        [[948, 469]],
 
        [[948, 492]],
 
        [[949, 493]],
 
        [[949, 494]],
 
        [[950, 494]],
 
        [[951, 495]],
 
        [[952, 495]],
 
        [[953, 494]],
 
        [[954, 494]],
 
        [[954, 493]],
 
        [[955, 492]],
 
        [[955, 478]],
 
   

In [14]:
green[:,:,1]

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [  0, 255, 255, ..., 255, 255, 255],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [5]:
green_coordinates = np.argwhere(imask > 0)
type(green_coordinates)

numpy.ndarray

In [9]:
plt.plot(x=)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False]])

In [6]:
alpha_shape = alphashape.alphashape(green_coordinates, 0.)

In [7]:
x, y = alpha_shape.exterior.coords.xy

In [8]:
x

array('d', [124.0, 2.0, 0.0, 0.0, 15.0, 44.0, 45.0, 99.0, 718.0, 718.0, 717.0, 124.0])

In [36]:
polygon_coordinates = np.array(list(zip(x.tolist(), y.tolist())), dtype=np.int32)
polygon_coordinates = polygon_coordinates.reshape((-1,1,2))
isClosed = True

# Blue color in BGR
color = (255, 0, 0)

# Line thickness of 2 px
thickness = 2

# Using cv2.polylines() method
# Draw a Blue polygon with
# thickness of 1 px
image = cv2.polylines(img, [polygon_coordinates],
                      isClosed, color, thickness)
while(1):

    cv2.imshow('image', image)
    if cv2.waitKey(20) & 0xFF == 27:
        break

cv2.destroyAllWindows()

KeyboardInterrupt: 

In [35]:
polygon_coordinates.dtype

dtype('float64')